'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import styles from './page.module.css'

export default function ReportPage() {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    const generateReport = async () => {
      try {
        const dataStr = sessionStorage.getItem('interview_data')
        if (!dataStr) {
          throw new Error("No interview data found. Please start a new interview.")
        }

        const payload = JSON.parse(dataStr)
        
        const res = await fetch('/api/report', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        })

        if (!res.ok) {
          throw new Error("Failed to generate report.")
        }

        const data = await res.json()
        if (data.error) throw new Error(data.error)
        
        setReport(data)
      } catch (err) {
        setError(err.message)
      } finally {
        setLoading(false)
      }
    }

    generateReport()
  }, [])

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.backgroundGlow} />
        <div className={styles.loadingContainer}>
          <div className={styles.spinner}></div>
          <div className={styles.loadingText}>AI is analyzing your architecture...</div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className={styles.container}>
        <div className={styles.backgroundGlow} />
        <div className={styles.glassCard}>
          <h1 className={styles.title}>Error</h1>
          <p className={styles.subtitle}>{error}</p>
          <Link href="/interview" style={{ color: '#38bdf8', marginTop: '20px', display: 'inline-block' }}>
            ← Back to Interview
          </Link>
        </div>
      </div>
    )
  }

  if (!report) return null

  const isHire = report.decision?.toLowerCase().includes('hire') && !report.decision?.toLowerCase().includes('no hire')

  return (
    <div className={styles.container}>
      <div className={styles.backgroundGlow} />
      <div className={styles.reportWrapper}>
        <div className={styles.glassCard}>
          
          <div className={styles.header}>
            <h1 className={styles.title}>Interview Feedback Report</h1>
            <p className={styles.subtitle}>Generated by your AI Engineering Manager</p>
          </div>

          <div className={styles.grid}>
            {/* Score & Decision */}
            <div className={styles.scoreSection}>
              <div className={styles.scoreCircle}>
                {report.score}
              </div>
              <div className={`${styles.decision} ${isHire ? styles.hire : styles.nohire}`}>
                {report.decision}
              </div>
              <div className={styles.level}>Assessed Level: {report.level}</div>
            </div>

            {/* Strengths */}
            <div className={styles.listCard}>
              <div className={`${styles.listTitle} ${styles.positive}`}>
                <span>👍</span> Core Strengths
              </div>
              <ul className={styles.list}>
                {report.strengths?.map((str, i) => (
                  <li key={i}>{str}</li>
                ))}
              </ul>
            </div>

            {/* Weaknesses */}
            <div className={styles.listCard}>
              <div className={`${styles.listTitle} ${styles.negative}`}>
                <span>💡</span> Areas for Improvement
              </div>
              <ul className={styles.list}>
                {report.weaknesses?.map((weak, i) => (
                  <li key={i}>{weak}</li>
                ))}
              </ul>
            </div>

            {/* Detailed Feedback */}
            <div className={styles.feedbackSection}>
              <div className={styles.listTitle}>
                <span>📝</span> Detailed Feedback
              </div>
              <p className={styles.feedbackText}>{report.feedback}</p>
            </div>
          </div>
          
          <div style={{ textAlign: 'center', marginTop: '40px' }}>
            <Link href="/" style={{ color: '#94a3b8', textDecoration: 'none', fontWeight: 600 }}>
              ← Return Home
            </Link>
          </div>

        </div>
      </div>
    </div>
  )
}
